Models/Doctor.cs
namespace MvcMascotas.Models
{
    public class Doctor
    {

        public int IdDoctor { get; set; }
        public int IdHospital { get; set; }
        public string Apellido { get; set; }
        public string Especialidad { get; set; }
        public int Salario { get; set; }
    }
}

Models/Hospital.cs
namespace MvcMascotas.Models
{
    public class Hospital
    {

        public int IdHospital { get; set; } 
        public string Nombre { get; set; }
        public string Direccion { get; set; }
        public string Telefono { get; set; }
        public int Camas { get; set; }
    }
}

Models/Mascota.cs
namespace MvcMascotas.Models
{
    public class Mascota
    {
        public int Edad { get; set; }
        public string Nombre { get; set; }

    }
}

Controllers/DoctoresController.cs
using Microsoft.AspNetCore.Mvc;
using MvcMascotas.Models;
using MvcMascotas.Repositories;

namespace MvcMascotas.Controllers
{
    public class DoctoresController : Controller
    {
        RepositoryDoctores repo;
        public DoctoresController()
        {

            this.repo = new RepositoryDoctores();
        }

        public IActionResult Index()
        {
            List<Doctor> doctores = this.repo.GetDoctores();
            return View(doctores);
        }

        public IActionResult DoctoresEspecialidad()
        {
            List<Doctor> doctores = this.repo.GetDoctores();
            return View(doctores);
        }


        [HttpPost]
        public IActionResult DoctoresEspecialidad(string especialidad)
        {
            List<Doctor> doctores = this.repo.FindDoctoresByEspecialidad(especialidad);
            return View(doctores);
        }

    }
}

Controllers/HomeController.cs
using Microsoft.AspNetCore.Mvc;
using MvcMascotas.Models;

namespace MvcMascotas.Controllers
{
    public class HomeController : Controller
    {
        public IActionResult Index()
        {
            return View();
        }

        public IActionResult VistaMascota()
        {
            List<Mascota> mascotas = new List<Mascota>();

                Mascota mascota = new Mascota();
                mascota.Nombre = "rata";
                mascota.Edad = 1;
                mascotas.Add(mascota);
            return View(mascota);
        }
    }
}

Controllers/HospitalesController.cs
using Microsoft.AspNetCore.Mvc;
using MvcMascotas.Models;
using MvcMascotas.Repositories;

namespace MvcMascotas.Controllers
{
    public class HospitalesController : Controller
    {
        RepositoryHospital repo;
        
        public HospitalesController() 
        {

            this.repo = new RepositoryHospital();
        }

        public IActionResult Index(int ?eliminar)
        {
            if(eliminar != null)
            {
                this.repo.DeleteHospital(eliminar.Value);
            }


            List<Hospital> hospitales = this.repo.GetHospitales();
            return View(hospitales);
        }

        public IActionResult Details(int idhospital)
        {
            Hospital hospital = this.repo.FindHospitalById(idhospital);
            return View(hospital);
        }

        public IActionResult Create()
        {
            return View();
        }

        [HttpPost]
        public IActionResult Create(Hospital hospital)
        {
            this.repo.InsertHospital(hospital.IdHospital, hospital.Nombre, hospital.Direccion, hospital.Telefono, hospital.Camas);
            ViewData["MENSAJE"] = "Hospital insertado!!";
            return View();
        }

        public IActionResult Edit(int idhospital)
        {
            Hospital hospital = this.repo.FindHospitalById(idhospital);
            return View(hospital);
        }

        [HttpPost]
        public IActionResult Edit(Hospital hospital)
        {
            this.repo.UpdateHospital(hospital.IdHospital, hospital.Nombre, hospital.Direccion, hospital.Telefono, hospital.Camas);
            ViewData["MENSAJE"] = "Hospital actualizado!!";
            return RedirectToAction("Index"); 
        }




    }
}

Views/Doctores/DoctoresEspecialidad.cshtml
@model List<Doctor>
<h1> Doctores Especialidad </h1>

<form method="post">
    <label> Intoduce Especialidad</label>
    <input type="text" name="especialidad" class="form-control" />
    <button> Buscar</button>
</form>


<table class="table table-bordered">
    <thead>
        <tr>
            <th> Apellido</th>
            <th> Especialidad</th>
            <th> Salario</th>
            <th> IdHospital</th>

        </tr>
    </thead>

    <tbody>
        @foreach (Doctor d in Model)
        {
            <tr>
                <td> @d.Apellido</td>
                <td> @d.Especialidad</td>
                <td> @d.Salario</td>
                <td> @d.IdHospital</td>


            </tr>
        }
    </tbody>

</table>

Views/Doctores/Index.cshtml
@model List<Doctor>

<h1> Doctores manin</h1>


<table class="table table-bordered">
    <thead>
        <tr>
            <th> Apellido</th>
            <th> Especialidad</th>
            <th> Salario</th>
            <th> Hospital Cod</th>
            <th> Detalles </th>
            <th> Editar </th>
            <th> Eliminar </th>
        </tr>
    </thead>

    <tbody>
        @foreach (Doctor d in Model)
        {
            <tr>
                <td> @d.Apellido</td>
                <td> @d.Especialidad</td>
                <td> @d.Salario</td>
                <td> @d.IdHospital</td>
                <td>
                    @Html.ActionLink("Details", "Details","Hospitales", new {idhospital = d.IdDoctor})
                </td>
                <td>
                    @Html.ActionLink("Edit", "Edit","Hospitales", new {idhospital = d.IdDoctor})
                </td>

                <td>
                    @Html.ActionLink("Delete", "Index","Hospitales", new {eliminar = d.IdDoctor})
                </td>

            </tr>
        }
    </tbody>

</table>

<p> <a class="navlink" asp-controller="Doctores" asp-action="DoctoresEspecialidad"> Crear Hospital </a></p>

Views/Home/Index.cshtml
<h1> JODIDO INDEX</h1>

Views/Home/VistaMascota.cshtml
@model Mascota
<h1> Vista mascota Model</h1>

<h2> Nombre: @Model.Nombre, EDAD: @Model.Edad</h2>

Views/Hospitales/Create.cshtml
<h1> Crear Hospital</h1>

<p>
    <a asp-asp-controller="Hospitales" asp-action="Index">
        Volver
    </a>
</p>


<form method="post">
    <label> Id Hospital</label>
    <input type = "number" name="idhospital" class="form-control" />

    <label> Nombre</label>
    <input type="text" name="nombre" class="form-control" />

    <label> Direccion</label>
    <input type="text" name="direccion" class="form-control" />

    <label> Telefono</label>
    <input type="text" name="telefono" class="form-control" />

    <label> Camas</label>
    <input type="number" name="camas" class="form-control" />

    <button class="btn btn-dark">
        Insertar Hospital
    </button>

</form>
<h1> @ViewData["MENSAJE"]</h1>

Views/Hospitales/Details.cshtml
@model Hospital
<h1> DETALLES </h1>

<p>
    <a asp-asp-controller="Hospitales" asp-action="Index">
 Volver
    </a>


</p>


<dl>

    <dt> Nombre: @Model.Nombre</dt>
    <dt> Nombre: @Model.IdHospital</dt>
    <dt> Nombre: @Model.Direccion</dt>
    <dt> Nombre: @Model.Telefono</dt>
    <dt> Nombre: @Model.Camas</dt>

</dl>

Views/Hospitales/Edit.cshtml
@model Hospital

<h1> Editar Hospital </h1>

<p>
    <a asp-asp-controller="Hospitales" asp-action="Index">
        Volver
    </a>
</p>


<form method="post">
    <input type="hidden" value="@Model.IdHospital" />
    <label>Nombre</label>
    <input type="text"name="nombre" class="form-control" value="@Model.Nombre" />
    <label>Direccion</label>
    <input type="text" name="direccion" class="form-control" value="@Model.Direccion" />
    <label>Telefono</label>
    <input type="text" name="telefono" class="form-control" value="@Model.Telefono" />
    <label>Camas</label>
    <input type="number" name="camas" class="form-control" value="@Model.Camas" />
    <br />
    <button class=" btn btn-info">
        Modificar Hospital
    </button>
</form>

<h1> @ViewData["MENSAJE"]</h1>

Views/Hospitales/Index.cshtml
@model List<Hospital>


<h1> Lista de Hospitales</h1>

<table class="table table-bordered">
    <thead>
        <tr>
            <th> Nombre</th>
            <th> direccion</th>
            <th> telefono</th>
            <th> camas</th>
            <th> Detalles </th>
            <th> Editar </th>
            <th> Eliminar </th>
        </tr>
    </thead>

    <tbody>
        @foreach(Hospital h in Model)
        {
           <tr>
                <td> @h.Nombre</td>
                <td> @h.Direccion</td>
                <td> @h.Telefono</td>
                <td> @h.Camas</td>
                <td> 
                    @Html.ActionLink("Details", "Details","Hospitales", new {idhospital = h.IdHospital})
                </td>
                <td>
                    @Html.ActionLink("Edit", "Edit","Hospitales", new {idhospital = h.IdHospital})
                </td>

                <td>
                    @Html.ActionLink("Delete", "Index","Hospitales", new {eliminar = h.IdHospital})
                </td>

           </tr> 
        }
    </tbody>

</table>

<p> <a class="navlink" asp-controller = "Hospitales" asp-action="Create"> Crear Hospital </a></p> 

Views/Hospitales/Prueba.cshtml
<h1> esto es una prueba</h1>

<h2> Esto es el mensaje @ViewData["MENSAJE"]</h2>

Views/Shared/_Layout.cshtml
<!doctype html>
<html lang="en" class="h-100" data-bs-theme="auto">
<head>
    <script src="/docs/5.3/assets/js/color-modes.js"></script>

    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="description" content="">
    <meta name="author" content="Mark Otto, Jacob Thornton, and Bootstrap contributors">
    <meta name="generator" content="Hugo 0.118.2">
    <title>Sticky Footer Navbar Template · Bootstrap v5.3</title>

    <link href="~/css/bootstrap.min.css" rel="stylesheet" />
    <link href="~/css/sticky.css" rel="stylesheet">
    <!-- Custom styles for this template -->
    <link href="~/css/sticky-footer-navbar.css" rel="stylesheet">

    <!-- Favicons -->
    <link rel="apple-touch-icon" href="/docs/5.3/assets/img/favicons/apple-touch-icon.png" sizes="180x180">
    <link rel="icon" href="/docs/5.3/assets/img/favicons/favicon-32x32.png" sizes="32x32" type="image/png">
    <link rel="icon" href="/docs/5.3/assets/img/favicons/favicon-16x16.png" sizes="16x16" type="image/png">
    <link rel="manifest" href="/docs/5.3/assets/img/favicons/manifest.json">
    <link rel="mask-icon" href="/docs/5.3/assets/img/favicons/safari-pinned-tab.svg" color="#712cf9">
    <link rel="icon" href="/docs/5.3/assets/img/favicons/favicon.ico">
    <meta name="theme-color" content="#712cf9">
</head>
<body class="d-flex flex-column h-100">
    <svg xmlns="http://www.w3.org/2000/svg" class="d-none">
        <symbol id="check2" viewBox="0 0 16 16">
            <path d="M13.854 3.646a.5.5 0 0 1 0 .708l-7 7a.5.5 0 0 1-.708 0l-3.5-3.5a.5.5 0 1 1 .708-.708L6.5 10.293l6.646-6.647a.5.5 0 0 1 .708 0z" />
        </symbol>
        <symbol id="circle-half" viewBox="0 0 16 16">
            <path d="M8 15A7 7 0 1 0 8 1v14zm0 1A8 8 0 1 1 8 0a8 8 0 0 1 0 16z" />
        </symbol>
        <symbol id="moon-stars-fill" viewBox="0 0 16 16">
            <path d="M6 .278a.768.768 0 0 1 .08.858 7.208 7.208 0 0 0-.878 3.46c0 4.021 3.278 7.277 7.318 7.277.527 0 1.04-.055 1.533-.16a.787.787 0 0 1 .81.316.733.733 0 0 1-.031.893A8.349 8.349 0 0 1 8.344 16C3.734 16 0 12.286 0 7.71 0 4.266 2.114 1.312 5.124.06A.752.752 0 0 1 6 .278z" />
            <path d="M10.794 3.148a.217.217 0 0 1 .412 0l.387 1.162c.173.518.579.924 1.097 1.097l1.162.387a.217.217 0 0 1 0 .412l-1.162.387a1.734 1.734 0 0 0-1.097 1.097l-.387 1.162a.217.217 0 0 1-.412 0l-.387-1.162A1.734 1.734 0 0 0 9.31 6.593l-1.162-.387a.217.217 0 0 1 0-.412l1.162-.387a1.734 1.734 0 0 0 1.097-1.097l.387-1.162zM13.863.099a.145.145 0 0 1 .274 0l.258.774c.115.346.386.617.732.732l.774.258a.145.145 0 0 1 0 .274l-.774.258a1.156 1.156 0 0 0-.732.732l-.258.774a.145.145 0 0 1-.274 0l-.258-.774a1.156 1.156 0 0 0-.732-.732l-.774-.258a.145.145 0 0 1 0-.274l.774-.258c.346-.115.617-.386.732-.732L13.863.1z" />
        </symbol>
        <symbol id="sun-fill" viewBox="0 0 16 16">
            <path d="M8 12a4 4 0 1 0 0-8 4 4 0 0 0 0 8zM8 0a.5.5 0 0 1 .5.5v2a.5.5 0 0 1-1 0v-2A.5.5 0 0 1 8 0zm0 13a.5.5 0 0 1 .5.5v2a.5.5 0 0 1-1 0v-2A.5.5 0 0 1 8 13zm8-5a.5.5 0 0 1-.5.5h-2a.5.5 0 0 1 0-1h2a.5.5 0 0 1 .5.5zM3 8a.5.5 0 0 1-.5.5h-2a.5.5 0 0 1 0-1h2A.5.5 0 0 1 3 8zm10.657-5.657a.5.5 0 0 1 0 .707l-1.414 1.415a.5.5 0 1 1-.707-.708l1.414-1.414a.5.5 0 0 1 .707 0zm-9.193 9.193a.5.5 0 0 1 0 .707L3.05 13.657a.5.5 0 0 1-.707-.707l1.414-1.414a.5.5 0 0 1 .707 0zm9.193 2.121a.5.5 0 0 1-.707 0l-1.414-1.414a.5.5 0 0 1 .707-.707l1.414 1.414a.5.5 0 0 1 0 .707zM4.464 4.465a.5.5 0 0 1-.707 0L2.343 3.05a.5.5 0 1 1 .707-.707l1.414 1.414a.5.5 0 0 1 0 .708z" />
        </symbol>
    </svg>

    <div class="dropdown position-fixed bottom-0 end-0 mb-3 me-3 bd-mode-toggle">
        <button class="btn btn-bd-primary py-2 dropdown-toggle d-flex align-items-center"
                id="bd-theme"
                type="button"
                aria-expanded="false"
                data-bs-toggle="dropdown"
                aria-label="Toggle theme (auto)">
            <svg class="bi my-1 theme-icon-active" width="1em" height="1em"><use href="#circle-half"></use></svg>
            <span class="visually-hidden" id="bd-theme-text">Toggle theme</span>
        </button>
        <ul class="dropdown-menu dropdown-menu-end shadow" aria-labelledby="bd-theme-text">
            <li>
                <button type="button" class="dropdown-item d-flex align-items-center" data-bs-theme-value="light" aria-pressed="false">
                    <svg class="bi me-2 opacity-50 theme-icon" width="1em" height="1em"><use href="#sun-fill"></use></svg>
                    Light
                    <svg class="bi ms-auto d-none" width="1em" height="1em"><use href="#check2"></use></svg>
                </button>
            </li>
            <li>
                <button type="button" class="dropdown-item d-flex align-items-center" data-bs-theme-value="dark" aria-pressed="false">
                    <svg class="bi me-2 opacity-50 theme-icon" width="1em" height="1em"><use href="#moon-stars-fill"></use></svg>
                    Dark
                    <svg class="bi ms-auto d-none" width="1em" height="1em"><use href="#check2"></use></svg>
                </button>
            </li>
            <li>
                <button type="button" class="dropdown-item d-flex align-items-center active" data-bs-theme-value="auto" aria-pressed="true">
                    <svg class="bi me-2 opacity-50 theme-icon" width="1em" height="1em"><use href="#circle-half"></use></svg>
                    Auto
                    <svg class="bi ms-auto d-none" width="1em" height="1em"><use href="#check2"></use></svg>
                </button>
            </li>
        </ul>
    </div>
    <header>
        <!-- Fixed navbar -->
        <nav class="navbar navbar-expand-md navbar-dark fixed-top bg-dark">
            <div class="container-fluid">
                <a class="navbar-brand" href="#">Navbar</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="collapse navbar-collapse" id="navbarNav">
                    <ul class="navbar-nav">
                        <li class="nav-item">
                            <a class="nav-link active" aria-current="page" href="#">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link" asp-action="VistaMascota" asp-controller="Home">Vista Mascota</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link" asp-action="Index" asp-controller="Hospitales">Hospitales</a>
                        </li>

                        <li class="nav-item">
                            <a class="nav-link" asp-action="Index" asp-controller="Doctores"> Doctores</a>
                        </li>

                    </ul>
                </div>
            </div>
        </nav>
    </header>

    <!-- Begin page content -->
    <main class="flex-shrink-0">
        <div class="container">
            @RenderBody()
            <button id="botonlayout"> PRUEBA</button>
            <h1 id="mensaje">   </h1>
        </div>
    </main>

    <footer class="footer mt-auto py-3 bg-body-tertiary">
        <div class="container">
            <span class="text-body-secondary">Place sticky footer content here.</span>
        </div>
    </footer>
    <script src="~/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/jquery-3.7.1.min.js"></script>

    <script>
        $(document).ready(function () {
            $("#botonlayout").click(function () {
                $("#mensaje").text("mensaje OK");
            })
        })

    </script>


</body>
</html>